### ISSUE TITLE
Dependency miss if all props are false

### ISSUE THREAD

**Issue by samueldepooter** [devinehowest/generator-devine-boilerplate#36]
```console
ERROR in ./src/js/script.js
Module build failed: ReferenceError: Unknown plugin "transform-object-rest-spread" specified in "/Users/Samuel/Desktop/test/.babelrc" at 2, attempted to resolve relative to "/Users/Samuel/Desktop/test"
    at /Users/Samuel/Desktop/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/Samuel/Desktop/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/Samuel/Desktop/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/Samuel/Desktop/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/Samuel/Desktop/test/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/Samuel/Desktop/test/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/Samuel/Desktop/test/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/Samuel/Desktop/test/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/Users/Samuel/Desktop/test/node_modules/babel-loader/lib/index.js:134:16)
 @ multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server ./~/react-dev-utils/webpackHotDevClient.js ./src/css/style.css ./src/js/script.js ./src/index.html
```

**Comment by geoffreydhuyvetters** [comment]
Error in https://github.com/devinehowest/generator-devine-boilerplate/blob/master/generators/app/templates/_package.json

Feel free to submit a PR, or will fix this on monday. For now installing the dependency manually should fix it, my bad.

**Comment by thibmaek** [comment]
Hadden er gisteren ook aan gedacht maar was laat om dan te PR'en 😄
Zal vanmiddag fix PR'en

**Comment by geoffreydhuyvetters** [comment]
Super. Merci.
Ik moet eens een goeie manier vinden om die generators te testen, niet evident

**Comment by geoffreydhuyvetters** [comment]
fixed met https://github.com/devinehowest/generator-devine-boilerplate/pull/38
